### ISSUE TITLE
[QUESTION] Using the master build setup as a development docker

### ISSUE THREAD

**Issue by vaidsu** [maxmcd/deno-docker#2]
This is cool initiative. Thanks for that. 

I actually realize that this is already there while I actually wrote the whole thing myself 😄 

I am going to use this instead, now, is your intention to have the source copied into $GOPATH and built into it into the docker is to somehow create a "shared folder" using -v option around that ? 

Basically how will you use the same setup for development? I am trying to use shared folders and making the docker slim here, but this seems to be taking a different approach. Just wanted to know.

Thanks in advance.

**Comment by maxmcd** [comment]
I'm a big fan of docker-compose. My dev setup for this container might be something like this:

**main.ts**
```typescript
console.log("hello world")
```
**Dockerfile**
```Dockerfile
FROM maxmcd/deno:slim
RUN mkdir /opt/src/
COPY . /opt/src/
CMD deno /src/main.ts
```
**docker-compose.yml**
```yaml
version: '3'
services: 
  deno:
    build: .
    volumes:
      - .:/opt/src/
```
From there you could `docker-compose run deno` or `docker-compose up`. Or skip docker-compose all together and yes just mount a volume to /opt/src/ (after making the directory).

The deno binary is just sitting in /opt/ at the moment, that might be a poor decision, should probably just have it in /usr/local/bin

**Comment by maxmcd** [comment]
Ok, I updated the slim build and added an example project: 8c57122a4b4a74d60eb585ed6a6563653c945eb7

**Comment by maxmcd** [comment]
I'm realizing I didn't read your issue well enough. Assuming you mean development on deno itself, I would clone the `ry/deno` repo and just use the `maxmcd/deno:build-cache` as the base image for a Dockerfile in the repo itself. Then just copy in the project files and `make` deno from within docker.

**Comment by vaidsu** [comment]
@maxmcd thanks for your quick response. I guess thats what I am using, that way I can use the local host volume and IDE etc. BTW are you working on any side project on deno in any of your fork? Do let me know, wish to see if I can collaborate 😄

**Comment by maxmcd** [comment]
There's a lambda branch, trying to get it built for AWS Lambda or another serverless environment so that a playground could be easily created.

There's also a deno2 branch, ry is currently working on a new build setup and replacing Go with c++. I think once that's done I'll try the lambda build again. 

Both are broken at the moment, but will likely sort them out once the deno2 work is merged to master.

**Comment by vaidsu** [comment]
Interesting i didnt know about the c++ part need to peek at it. Yes saw ur
lamba.. Need to catch up. Is there any slack or discord room by any chance
?

**Comment by maxmcd** [comment]
Not that I know of. I just saw this: https://github.com/ry/deno/pull/209#issuecomment-395985554
and this: https://github.com/ry/deno/tree/deno2/deno2
