### ISSUE TITLE
deno2

### ISSUE THREAD

**Issue by superlbr** [maxmcd/deno-docker#3]
hope support branch choose

**Comment by maxmcd** [comment]
There is a branch that's working to support deno2: https://github.com/maxmcd/deno-docker/tree/deno2

Was running into compilation errors yesterday, will give it another try.

**Comment by maxmcd** [comment]
Should probably leave this open until the branch is fully supported.

**Comment by superlbr** [comment]
deno2 already merged into master

**Comment by maxmcd** [comment]
Cool, thanks! Will see if I can get it built successfully

**Comment by maxmcd** [comment]
Looks like the build was just broken in debian. Switched to ubuntu and it's working now. There's a new `deno2` image available and info added to the readme. Closing for now.

**Comment by superlbr** [comment]
looks deno2_travis added

**Comment by maxmcd** [comment]
Looks like it's replaced the old source and still doesn't execute any code dynamically. Fixing the dockerfile now using the travis build details

**Comment by superlbr** [comment]
glad to see golang is removed

**Comment by superlbr** [comment]
version 0.0.1 released

**Comment by maxmcd** [comment]
Cool, fixed the build, I think it's back to functional now

**Comment by maxmcd** [comment]
whoops, there are binary releases now, going to rewrite with just those pulled down

**Comment by maxmcd** [comment]
Ok, we've got release builds with jessie and jessie slim. Mastet build is still around for reference. Closing this issue for now.
