### ISSUE TITLE
Automatically build new deno versions and push version tagged images to hub

### ISSUE THREAD

**Issue by superlbr** [maxmcd/deno-docker#5]
I don't know version of deno in your docker util pull down.
So is there possibilty that use such like dependencies.io.
Once deno [release](https://github.com/denoland/deno/releases.atom) -> notify deno-docker -> run travis -> update readme -> release docker with version in tag

**Comment by maxmcd** [comment]
totally, will do

**Comment by maxmcd** [comment]
I think I'm going to punt on this and just manually update it for now until deno is more fully functioning. Will leave this issue open to track progress.

**Comment by superlbr** [comment]
reasonable

**Comment by maxmcd** [comment]
The repo now rebuilds every 24hrs
