### ISSUE TITLE
Issue when running deno on a machine with 1 CPU

### ISSUE THREAD

**Issue by pietvanzoen** [maxmcd/deno-docker#7]
I'm having issues running Deno in this image, specifically when running in a container on an Ubuntu server. I'm a little out of my depth here so I appreciate this may not be an issue with you package, but perhaps you can still help.

Running locally on MacOS the image runs as expected.

MacOS: 10.14.4 (18E226)
Docker version 18.09.2, build 6247962

When attempting to run any file with Deno inside the image on an Ubuntu machine Deno just ends up hanging. 

```
> docker run -it maxmcd/deno:latest bash
root@eedc4941409a:/# deno --version
deno: 0.3.7
v8: 7.4.238
typescript: 3.4.1
root@eedc4941409a:/# echo "console.log('foo')" > foo.ts
root@eedc4941409a:/# deno -AD ./foo.ts
DEBUG RS - mkdir -p /root/.cache/deno/gen
DEBUG RS - set dir perm to 493
DEBUG RS - mkdir -p /root/.cache/deno/deps
DEBUG RS - set dir perm to 493
DEBUG RS - mkdir -p /root/.cache/deno/deps/http
DEBUG RS - set dir perm to 493
DEBUG RS - mkdir -p /root/.cache/deno/deps/https
DEBUG RS - set dir perm to 493
DEBUG RS - root /root/.cache/deno
DEBUG RS - gen /root/.cache/deno/gen
DEBUG RS - deps /root/.cache/deno/deps
DEBUG RS - deps_http /root/.cache/deno/deps/http
DEBUG RS - deps_https /root/.cache/deno/deps/https
DEBUG RS - Deno isolate init with snapshots.
DEBUG RS - resolve_module specifier ./foo.ts referrer .
DEBUG RS - msg_from_js Start sync true
DEBUG JS - cwd /
DEBUG JS - args [ "./foo.ts" ]
DEBUG RS - resolve_module specifier ./foo.ts referrer .
DEBUG RS - main_module file:///foo.ts
DEBUG RS - fetch_module_meta_data. specifier file:///foo.ts referrer .
DEBUG RS - resolve_module specifier file:///foo.ts referrer .
DEBUG RS - module_name: file:///foo.ts, filename: /foo.ts
DEBUG RS - fetch local or reload file:///foo.ts is_module_remote false
DEBUG RS - found local source
```

After this it hangs indefinitely. 

Ubuntu 18.04.2 LTS (Bionic Beaver)
Docker version 18.09.5, build e8ff056

Any tips would be appreciated.

**Comment by maxmcd** [comment]
Looks like a bug to me!

Thanks for the detailed report. Would you mind running `docker inspect maxmcd/deno:latest` and pasting the `RepoDigests` section here? Should be something like: 
```
"maxmcd/deno@sha256:24df4ae704b4848445d4c5ebd145853246231b6f7f4becdc24c798361812d264"
```

When I run your example locally on the latest version of maxmcd/deno it works for me, want to confirm that you're experiencing the bug on the version I'm testing before continuing.

**Comment by pietvanzoen** [comment]
Ah... I tried just installing Deno on the server and seeing if it ran that way. It did not. Same issue. So it seems it's an issue with Deno rather than your package. :/

Either way. Digest matches: `maxmcd/deno@sha256:24df4ae704b4848445d4c5ebd145853246231b6f7f4becdc24c798361812d264`

**Comment by pietvanzoen** [comment]
Have posted an issue here: https://github.com/denoland/deno/issues/2124

**Comment by pietvanzoen** [comment]
Update: Issue is when running deno on a machine with only 1 CPU. https://github.com/denoland/deno/issues/2124#issuecomment-484092803

**Comment by maxmcd** [comment]
fascinating, thanks for the update, will leave open until it's resolved upstream
